name: deploy
on:
  push:
    branches:
      - master
jobs:
  build_for_deploy:
    uses: ./.github/workflows/build.yaml
  deploy:
    needs: build_for_deploy
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
      
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
    
      - name: Initialize Terraform
        run: terraform init

      - name: Validate Terraform configuration
        run: terraform validate

      - name: Apply Terraform configuration
        run: terraform apply -auto-approve

      - name: Destroy Terraform resources
        if: github.event_name == 'workflow_dispatch'
        run: terraform destroy -auto-approve
      