name: deploy
on:
  push:
    branches:
      - master
jobs:
  build_for_deploy:
    uses: ./.github/workflows/build.yaml
  deploy:
    needs: build_for_deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
      
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
      
      - name: setup aws credentails 
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          # Role has been created in AWS IAM that allows GitHub Actions to assume the role and access AWS resources.
          role-to-assume: arn:aws:iam::836633177159:role/github-ci-access-role
          # duration-seconds is the time in seconds that the temporary credentials will be valid, defult is 3600 seconds (1 hour).
          role-duration-seconds: 300 # 5 minutes
          aws-region: ap-south-1
        run: |
          echo "AWS credentials configured successfully."
          aws sts get-caller-identity

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
    
      - name: Initialize Terraform
        run: terraform init

      - name: Validate Terraform configuration
        run: terraform validate

      - name: Apply Terraform configuration
        run: terraform apply -auto-approve

      - name: Destroy Terraform resources
        if: github.event_name == 'workflow_dispatch'
        run: terraform destroy -auto-approve
      