name: deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Set up environment (if needed)
        run: |
          echo "Setting up environment..."
          pwd
          mkdir -p package

      - name: Build application
        run: |
          cp lambda_function.py package/
          zip -r "lambda.zip" package/

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
    
      - name: Initialize Terraform
        run: terraform init

      - name: Validate Terraform configuration
        run: terraform validate

      - name: Apply Terraform configuration
        run: terraform apply -auto-approve