name: pull_request
# This workflow is triggered on pull requests to the master branch.
# It builds the application and uploads the artifacts for review.
on:
  pull_request:
    branches:
      - master
jobs:
  build_for_pull_request:
    uses: ./.github/workflows/build.yaml
